# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73095dc5ed3a67db8a4772ffa5d5f7eaa2e1b367becbae453e75fe92b4ebb3b7076efd175475ed82acee48616ca7f8364a9340e40ccfa57dbfc1116b61a52a3e

test:
  secret_key_base: 7915729fb9552b778a3c51a968c380fb9581e4e50b8f308584e9fdf1c8457f16eb0a3b017f2fcd4960b90f115d7cd2f680d5e889539ff0cb9c92e1c3f19b75c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
